### ISSUE TITLE
incompatible php version - composer.json issue

### ISSUE THREAD

**Issue by eisbehr-** [ho-nl/magento2-Ho_Import#11]
When i try to import your module by the given commands in your readme, i'm always getting the following error message by composer:

>  [InvalidArgumentException]                                                                                  
  Package honl/magento2-import at version  has a PHP requirement incompatible with your PHP version (7.2.17)  

Is there anything known about this issue?! Installing other modules was no problems so far.

**Comment by eisbehr-** [comment]
Isn't you `composer.json` wrong there? It seems there is a pipe missing fo the `or` constraint:

```JS
 "php": "~7.1.0|~7.2.0",
```

Should be:


```JS
 "php": "~7.1.0||~7.2.0",
```

**Comment by Maksold** [comment]
I have the same problem. 😞

**Comment by PascalBrouwers** [comment]
Fixed in https://github.com/ho-nl/magento2-Ho_Import/commit/25e605bab4734a85d0101e0fce4e5805060cbecf
