### ISSUE TITLE
Profile creating

### ISSUE THREAD

**Issue by narmontase** [ho-nl/magento2-Ho_Import#9]
Hi,
Can't create profile. I used example http://cloud.h-o.nl/500cacad72dc 
As I understand this part has to be different for me:
<item name="product" xsi:type="object">ReachDigital\Waardijak\Import\ProductImport</item>
For example how to create profile for ExampleProfile.php that you have included?

**Comment by paales** [comment]
1. Create your own module.
2. Add your profile to your di.xml
3. flush cache
4. Should now turn up in the `ho:import:run` command

```xml
<?xml version="1.0"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
    <type name="Ho\Import\Model\ImportProfilePool">
        <arguments>
            <argument name="profiles" xsi:type="array">
                <item name="my_import" xsi:type="object">Company\ImportModule\Import\ ExampleProfile </item>
            </argument>
        </arguments>
    </type>
</config>
```

**Comment by Puigdemunt** [comment]
I get "Profile not in profilelist: my_import"

**Comment by paales** [comment]
Please check if the module is enabled and working properly.
